ARDUINO_VARIANT = nodemcuv2
SERIAL_PORT = /dev/ttyUSB0

USER_DEFINE  = -D_SSID_=\"MosEisleySpaceport\" 
USER_DEFINE += -D_WIFI_PASSWORD_=\"supersonic\"
USER_DEFINE += -D_MDNS_NAME_=\"edubot\"

include ${HOME}/dev/git/Esp8266-Arduino-Makefile/esp8266Arduino.mk
